name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate dependencies
        uses: php-actions/composer@v6
        with:
          command: validate

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: gd
          command: install --no-interaction
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.sha }}
          path: .
