name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate dependencies
        uses: php-actions/composer@v6
        with:
          command: validate

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: gd
          command: install --no-interaction

      - run: ls -aF

      - run: echo ".vendor/bin" >> $GITHUB_PATH

      - run: drush
